import {Platform} from 'react-native';
import LocalizedStrings from 'react-native-localization';

export default Strings = new LocalizedStrings({
  en: {
    common: {
      welcome: 'Welcome to Intentional Walk!!',
      next: "Next",
      today: "Today",
      yesterday: "Yesterday",
      noWalks: "No Recorded Walks",
      noWalksYet: "No Walks Yet",
      home: 'Home',
      back: 'Back',
      myRecordedWalks: 'My Recorded Walks',
      about: 'iWalk Information',
      programPartners: 'Program Partners',
      whereToWalk: 'Where to Walk',
      emailUs: 'Email Us',
      privacyPolicy: 'Privacy Policy',
      signOut: 'Sign out',
      steps: 'steps',
      miles: 'miles',
      mins: 'mins',
      morningWalk: 'Morning Walk',
      afternoonWalk: 'Afternoon Walk',
      eveningWalk: 'Evening Walk',
      okay: 'Okay',
      pleaseWait: 'Please wait...',
      serverErrorTitle: 'Unexpected error',
      serverErrorMessage: "We could not communicate with the Intentional Walk Server. Please check your Internet connection and try again.",
      date: 'MMMM D',
      range: '{0} - {1}',
      rangeFrom: 'MMMM D',
      rangeTo: 'MMMM D, YYYY',
    },
    notifications: {
      repeatingRecordingReminder: "You've been walking for over an hour. Don't forget to stop recording your walk if you're done!",
    },
    partners: {
      thanks: 'Special thanks to all the iWalk partners!',
      text: 'Intentional Walk is run by the SF Department of Public Health. It is funded by USDA SNAP, an equal opportunity provider and employer. Community partners include the California Department of Public Health, Code for San Francisco, San Francisco Giants, and the SF Recreation and Parks Department.',
    },
    recorder: {
      finish: 'Finish',
      resume: 'Resume',
      stopAndSave: 'Stop & Save',
      stop: 'Stop',
      pause: 'Pause',
      paused: 'Paused',
      recording: 'Recording',
      save: 'Save {0}',
    },
    welcome: {
      select: 'Please Select a language',
      start: 'Start'
    },
    signUp: {
      about: 'Intentional Walk is a FREE community walking program that runs from {0}. The program is open to CalFresh/MediCal-eligible San Francisco residents. Top walkers will be eligible for prizes from the San Francisco Giants including game tickets, signed team gear, and a special grand prize! Sign up below to get started!',
      name: 'Name',
      email: 'Email',
      zipCode: 'Zip Code',
      age: 'Age',
      required: '* all fields required',
      agree: 'By signing up, I agree to the {0}.',
      policy: 'Privacy Policy',
      submit: 'Submit',
      ageAlertTitle: 'Age Restriction',
      ageAlertMessage: 'You must be at least 18 years old to participate in iWalk.',
      emailAlertTitle: 'Email Required',
      emailAlertMessage: 'Please enter a valid email address.',
      zipAlertTitle: 'Zip Code Required',
      zipAlertMessage: 'Please enter a 5-digit Zip Code.',
    },
    info: {
      youreSignedUp: "You’re signed up!",
      fromHereText: "From here, participation is easy:",
      walk: "Walk!",
      walkText: "This app will count your total steps taken each day, just carry your phone with you when you’re walking.",
      record: "Record!",
      recordText: "Use this feature to track your walks. Challenge yourself to increase distance and time!",
      win: "Win!",
      winText: "At the end of the program, the top 10 walkers will be contacted by email to claim their prize. Prizes include SF Giants game tickets, signed team gear, and a special grand prize!",
    },
    permissions: {
      thingsToKnow: "Things to know.",
      takeALookText: "Take a look at this information before you get started.",
      settingsText: `The iWalk App uses ${Platform.select({ios: 'Apple Health', android: 'Google Fit'})} to keep track of your steps. In the next screens, you will be asked to allow iWalk to use this information.`,
      prizeText: `To win a prize through Intentional Walk, you must allow the iWalk App to use ${Platform.select({ios: 'Apple Health', android: 'Google Fit'})} information. All information will be kept private and used only for the Intentional Walk program.`,
      googleText: "Google Fit requires a Google account, if you do not have one, learn how to get one {0}.",
      getOneHere: "here",
    },
    home: {
      stepsToday: "steps today",
      milesSuffix: "",
      milesToday: "miles today",
      overallStepTotal: "overall step total",
      stepsThisMonth: "total steps this month",
      whereToWalk: "Need a place to walk?",
      myRecordedWalks: "My Recorded Walks Today",
      allRecordedWalks: "All Recorded Walks",
      noWalksYetText: "Start a new walk by pressing the record button at the bottom of the screen.",
      recordAWalk: 'Record a New Walk',
      getReadyAlert1: 'Get ready to start the challenge!',
      getReadyAlert2: 'On {0}, your step total will reset and your steps will start being counted towards winning prizes.',
    },
    whereToWalk: {
      options: 'The San Francisco Rec & Parks Department has many activity options!',
      parksAndRecCenters: "Parks & Rec Centers",
    	hikingTrailsInSF: "Hiking Trails in SF",
      guidedWalks: "Guided Walks",
      exerciseAndFitnessActivities: "Exercise & Fitness Activities",
    },
    about: {
      what: 'What is Intentional Walk?',
      whatText: 'Intentional Walk is a FREE community walking program that runs from {0}. The program is open to CalFresh/MediCal-eligible San Francisco residents. Prizes will be awarded to the top walkers at the end of the program.',
      dates: 'What are the key dates?',
      datesText: 'On {0}, your steps will start at zero and the walking challenge will begin! All of your steps from {1} will count towards winning a prize. After the program is over, you can use the app, but no additional prizes will be awarded.',
      prize: 'How do I win a prize?',
      prizeText: 'At the end of the program, the top 10 walkers will be contacted by email to claim their prize. Prizes include SF Giants game tickets, signed team gear, and a special grand prize!',
    },
  },
  es: {
    common: {
      welcome: 'Bienvenido al Paseo Intencional!!',
      next: "Siguiente",
      today: "Hoy",
      yesterday: "Ayer",
      noWalks: "No hay caminatas grabadas",
      noWalksYet: "Todavía no hay caminatas",
      home: 'Hogar',
      back: 'Atrás',
      myRecordedWalks: 'Mis Caminatas Grabadas',
      about: 'Información de iWalk',
      programPartners: 'Socios del Programa',
      whereToWalk: 'Donde Caminar',
      emailUs: 'Envíanos un correo electrónico',
      privacyPolicy: 'Política de Privacidad',
      signOut: 'Sign out',
      steps: 'pasos',
      miles: 'millas',
      mins: 'minutos',
      morningWalk: 'Caminata Matutina',
      afternoonWalk: 'Caminata por la Tarde',
      eveningWalk: 'Caminata Nocturna',
      okay: 'Está bien',
      pleaseWait: 'Please wait...',
      serverErrorTitle: 'Unexpected error',
      serverErrorMessage: "We could not communicate with the Intentional Walk Server. Please check your Internet connection and try again.",
      date: 'Do [de] MMMM',
      range: '{0} al {1}',
      rangeFrom: 'Do [de] MMMM',
      rangeTo: 'Do [de] MMMM [del] YYYY',
    },
    partners: {
      thanks: '¡Un agradecimiento especial a todos los socios de iWalk!',
      text: 'El Paseo Intencional es dirigido por el Departamento de Salud Pública de SF. Está financiado por USDA SNAP, un proveedor y empleador que ofrece igualdad de oportunidades. Los socios comunitarios incluyen el Departamento de Salud Pública de California, Código para San Francisco, los Gigantes de San Francisco y el Departamento de Recreación y Parques de SF.',
    },
    recorder: {
      finish: 'Terminar',
      resume: 'Reiniciar',
      stopAndSave: 'Parar y Guardar',
      stop: 'Parar',
      pause: 'Pausa',
      paused: 'Pausada',
      recording: 'Grabación',
      save: 'Guardando {0}',
    },
    welcome: {
      select: 'Por favor seleccione un idioma.',
      start: 'Iniciar'
    },
    signUp: {
      about: 'El Paseo Intencional es un programa GRATUITO de caminata comunitaria que se llevará a cabo del {0}. El programa está abierto para residentes de San Francisco elegibles para CalFresh / MediCal. ¡Los mejores caminantes serán elegibles para recibir premios de los Gigantes de San Francisco, incluyendo boletos para el juego, artículos firmados por el equipo y un gran premio especial! ¡Inscríbase para comenzar!',
      name: 'Nombre',
      email: 'Correo electrónico',
      zipCode: 'Código postal',
      age: 'Edad',
      required: '*Todos los campos son requeridos',
      agree: 'Al registrarme, acepto la {0}.',
      policy: 'Política de Privacidad',
      submit: 'Enviar',
      ageAlertTitle: 'Restricción de Edad',
      ageAlertMessage: 'Debes tener al menos 18 años para participar en iWalk.',
      emailAlertTitle: 'Correo electrónico',
      emailAlertMessage: 'Por favor, introduce una dirección de correo electrónico válida.',
      zipAlertTitle: 'Código Postal Requerido',
      zipAlertMessage: 'Por favor ingresa un código postal de 5 dígitos.',
    },
    info: {
      youreSignedUp: "Estas registrado!",
      fromHereText: "Desde aquí, participar es fácil.",
      walk: "¡Caminar!",
      walkText: "Esta aplicación contará los pasos totales que tomas cada día, solo lleva tu teléfono contigo mientras caminas.",
      record: "¡Grabar!",
      recordText: "Usa esta función para grabar tus caminatas. ¡Desafíate a ti mismo para aumentar el tiempo y la distancia!",
      win: "¡Ganar!",
      winText: "Al final del programa, los 10 mejores caminantes serán contactados por correo electrónico para reclamar su premio.¡Los premios incluyen entradas para el juego de los Gigantes de SF, artículos firmados por el equipo y un gran premio especial!",
    },
    permissions: {
      thingsToKnow: "Cosas que debes saber.",
      takeALookText: "Echa un vistazo a esta información antes de comenzar.",
      settingsText: `La aplicación iWalk utiliza datos recopilados por ${Platform.select({ios: 'Apple Health', android: 'Google Fit'})} para grabar con precisión tus pasos diarios. En las siguientes pantallas, se te pedirá que des permiso para que iWalk acceda a esta información.`,
      prizeText: `Todos los participantes que deseen ser elegibles para premios a través del Paseo Intencional deben dar permiso para acceder a esta información. Todos los datos proporcionados se mantendrán privados y se utilizarán estrictamente para el propósito del programa de Paseo Intencional.`,
      googleText: "Google Fit requiere una cuenta de Google, si no tiene una, aprenda cómo obtenerla {0}.",
      getOneHere: "aquí",
    },
    home: {
      stepsToday: "pasos hoy",
      milesSuffix: "",
      milesToday: "millas hoy",
      overallStepTotal: "recuento total de pasos",
      stepsThisMonth: "total steps this month",
      whereToWalk: "¿Necesitas un lugar para caminar?",
      myRecordedWalks: "Mis Caminatas Grabadas Hoy",
      allRecordedWalks: "Todas las Caminatas Grabadas",
      noWalksYetText: "Comienza una nueva caminata presionando el botón de grabación en la parte inferior de la pantalla.",
      recordAWalk: 'Grabar una Nueva Caminata',
      getReadyAlert1: '¡Prepárate para comenzar el desafío!',
      getReadyAlert2: 'El {0} tu recuento total de pasos reiniciará y tus pasos comenzarán a ser contados para ganar premios.',
    },
    whereToWalk: {
      options: '¡El Departamento de Parques y Recreación de San Francisco tiene muchas opciones de actividades!',
      parksAndRecCenters: "Parques y Centros de Recreación",
    	hikingTrailsInSF: "Rutas de Senderismo en SF",
      guidedWalks: "Caminatas Guiadas",
      exerciseAndFitnessActivities: "Ejercicio y Actividades Físicas",
    },
    about: {
      what: '¿Qué es el Paseo Intencional?',
      whatText: 'El Paseo Intencional es un programa GRATUITO de caminata comunitaria que se llevará a cabo del {0}. El programa está abierto para residentes de San Francisco elegibles para CalFresh / MediCal. Se otorgarán premios a los mejores caminantes al final del programa.',
      dates: '¿Cuáles son las fechas importantes?',
      datesText: 'El {0}, tus pasos comenzarán en cero y el desafío de caminar comenzará! Todos tus pasos del {1} contarán para ganar un premio. Una vez finalizado el programa, puedes utilizar la aplicación, pero no se otorgarán premios adicionales.',
      prize: '¿Cómo gano un premio?',
      prizeText: 'Al final del programa, los 10 mejores caminantes serán contactados por correo electrónico para reclamar su premio.¡Los premios incluyen entradas para el juego de los Gigantes de SF, artículos firmados por el equipo y un gran premio especial!',
    },
  },
  zh: {
    common: {
      welcome: '歡迎來到 Intentional Walk!!',
      next: "下一步",
      today: "今天",
      yesterday: "昨天",
      noWalks: "無行走記錄",
      noWalksYet: "還沒有行走",
      home: '家',
      back: '返回',
      myRecordedWalks: '我的步行記錄',
      about: 'iWalk信息',
      programPartners: '計劃合作夥伴',
      whereToWalk: '去哪裡',
      emailUs: '電郵我們',
      privacyPolicy: '隱私條款',
      signOut: 'Sign out',
      steps: '步',
      miles: '英里',
      mins: '分鐘',
      morningWalk: '早上散步',
      afternoonWalk: '下午散步',
      eveningWalk: '傍晚散步',
      okay: '同意',
      pleaseWait: 'Please wait...',
      serverErrorTitle: 'Unexpected error',
      serverErrorMessage: "We could not communicate with the Intentional Walk Server. Please check your Internet connection and try again.",
      date: 'M月D日',
      range: '{0}至{1}',
      rangeFrom: 'YYYY[年]M[月]D[日]',
      rangeTo: 'M月D日',
    },
    partners: {
      thanks: '特別鳴謝所有iWalk贊助商!',
      text: 'Intentional Walk是由舊金山公共衛生局負責. USDA SNAP資助的一项機會均等提供者和雇主的方案. 社區合作夥伴包括加州公共衛生局, Code of San Franciaco, 舊金山巨人隊和舊金山康樂與公園部.',
    },
    recorder: {
      finish: '完成',
      resume: '重新開始',
      stopAndSave: '停止並保存',
      stop: '停止',
      pause: '暫停',
      paused: '暫停',
      recording: '記錄',
      save: '保存{0}',
    },
    welcome: {
      select: '請選擇一種語言.',
      start: '開始'
    },
    signUp: {
      about: 'Intentional Walk 是一項於{0}免費運行的社區步行計劃.該計劃向有資格參加CalFresh / Medical的舊金山居民開放. 頂級步行者將有資格獲得舊金山巨人隊的獎品, 其中包括比賽門票, 簽名的裝備和特別獎品! 在下面註冊即可開始!',
      name: '名稱',
      email: '電子郵件',
      zipCode: '郵政編碼',
      age: '年齡',
      required: '* 需填寫字段',
      agree: '簽署即表示我同意 {0}.',
      policy: '隱私條款',
      submit: '提交',
      ageAlertTitle: '年齡限制',
      ageAlertMessage: '您必須年滿18歲才能參與iWalk。',
      emailAlertTitle: '需填電子郵件',
      emailAlertMessage: '請輸入有效的電子郵件地址.',
      zipAlertTitle: '需填郵政編碼',
      zipAlertMessage: '請輸入5位數的郵政編碼。',
    },
    info: {
      youreSignedUp: "您已註冊!",
      fromHereText: "從這裡開始，參與很容易.",
      walk: "步行!",
      walkText: "這個應用程式會計算您每天要走的總步數，步行時只需隨身攜帶手機即可.",
      record: "記錄!",
      recordText: "使用此功能跟蹤您的行走步數.  增加行走距離和時間來挑戰自我!",
      win: "獲勝!",
      winText: "在該計劃結束後會通過電子郵件與前10名步行者聯繫, 以領取獎品.  獎品包括SF巨人的門票,簽名製服和特別獎品!",
    },
    permissions: {
      thingsToKnow: "事情需知.",
      takeALookText: "在開始之前請看以下信息.",
      settingsText: `iwalk應用程序使用${Platform.select({ios: 'Apple Health', android: 'Google Fit'})}來跟蹤您的步數. 在下一個屏幕中您將看到允許iWalk使用的信息.`,
      prizeText: `您必須允許iWalk應用程序使用${Platform.select({ios: 'Apple Health', android: 'Google Fit'})}信息才能贏取“Intentional Walk"獎品. 所有信息將保密, 僅用於"Intentional Walk"計劃。`,
      googleText: "Google Fit需要一個Google帳戶, 如果您沒有Google帳戶, {0}.",
      getOneHere: "請在此處了解如何獲取帳戶",
    },
    home: {
      stepsToday: "今天的步數",
      milesSuffix: "英里",
      milesToday: "今天的路程",
      overallStepTotal: "總步數",
      stepsThisMonth: "total steps this month",
      whereToWalk: "去哪裡?",
      myRecordedWalks: "我今天的步行記錄",
      allRecordedWalks: "所有的步行記錄",
      noWalksYetText: "按下屏幕底部的“錄製”按鈕來開始新的步行.",
      recordAWalk: '記錄新步數',
      getReadyAlert1: '準備好開始挑戰！',
      getReadyAlert2: '從{0}起, 您的步數總數將會重置並且您的步數將開始計入獲獎獎數中.',
    },
    whereToWalk: {
      options: '舊金山娛樂與公園部有很多活動可供選擇!',
      parksAndRecCenters: "公園和娛樂中心",
    	hikingTrailsInSF: "舊金山的遠足徑",
      guidedWalks: "導遊步行",
      exerciseAndFitnessActivities: "運動與健身活動",
    },
    about: {
      what: '什麽是Intentional Walk?',
      whatText: 'Intentional Walk 是一項於{0}免費運行的社區步行計劃.該計劃向有資格參加CalFresh / Medical的舊金山居民開放.',
      dates: '關鍵日期?',
      datesText: '挑戰从{0}起, 您的步行數將從零開始! {1}, 您所有的步行數都將計入獎品中. 計劃結束後, 您可以使用該應用程序，但不會獲得其他獎品.',
      prize: '我如何赢取獎品?',
      prizeText: '在該計劃結束後會通過電子郵件與前10名步行者聯繫, 以領取獎品.  獎品包括SF巨人的門票,簽名製服和特別獎品!',
    },
  }
});
