import {Platform} from 'react-native';
import LocalizedStrings from 'react-native-localization';

const Strings = new LocalizedStrings({
  en: {
    common: {
      welcome: 'Welcome to Intentional Walk!!',
      next: 'Next',
      today: 'Today',
      yesterday: 'Yesterday',
      noWalks: 'No Recorded Walks',
      noWalksYet: 'No Walks Yet',
      home: 'Home',
      back: 'Back',
      myRecordedWalks: 'My Recorded Walks',
      about: 'iWalk Information',
      programPartners: 'Program Partners',
      topWalkers: 'Top Walkers',
      whereToWalk: 'Where to Walk',
      emailUs: 'Email Us',
      contestRules: 'Contest Rules',
      privacyPolicy: 'Privacy Policy',
      signOut: 'Sign out',
      deleteUser: 'Delete Account',
      steps: 'steps',
      miles: 'miles',
      mins: 'mins',
      morningWalk: 'Morning Walk',
      afternoonWalk: 'Afternoon Walk',
      eveningWalk: 'Evening Walk',
      okay: 'Okay',
      pleaseWait: 'Please wait...',
      serverErrorTitle: 'Unexpected error',
      serverErrorMessage:
        'We could not communicate with the Intentional Walk Server. Please check your Internet connection and try again.',
      date: 'MMMM D',
      range: '{0} - {1}',
      rangeFrom: 'MMMM D',
      rangeTo: 'MMMM D, YYYY',
      dateSlash: 'MM/DD/YYYY',
      save: 'Save',
    },
    notifications: {
      repeatingRecordingReminder:
        "You've been walking for over an hour. Don't forget to stop recording your walk if you're done!",
    },
    partners: {
      thanks: 'Special thanks to all the iWalk partners!',
      text: 'Intentional Walk is run by the SF Department of Public Health. It is funded by USDA SNAP, an equal opportunity provider and employer. Community partners include the California Department of Public Health, Code for San Francisco, San Francisco Giants, and the SF Recreation and Parks Department.',
    },
    recorder: {
      finish: 'Finish',
      resume: 'Resume',
      stopAndSave: 'Stop & Save',
      stop: 'Stop',
      pause: 'Pause',
      paused: 'Paused',
      recording: 'Recording',
      save: 'Save {0}',
    },
    welcome: {
      select: 'Please Select a language',
      start: 'Start',
    },
    signUp: {
      about:
        'Intentional Walk is a FREE community walking program that runs from {0}. The program is open to CalFresh/MediCal-eligible San Francisco residents. Top walkers will be eligible for prizes from the San Francisco Giants including game tickets, signed team gear, and a special grand prize! Sign up below to get started!',
      name: 'Name',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      zipCode: 'Zip Code',
      age: 'Age',
      required: '* all fields required',
      agree: 'By signing up, I agree to the {0} and {1}.',
      policy: 'Privacy Policy',
      contestRules: 'Contest Rules',
      submit: 'Submit',
      ageAlertTitle: 'Age Restriction',
      ageAlertMessage:
        'You must be at least 18 years old to participate in iWalk.',
      ageMaxMessage: 'Please enter a valid age.',
      emailAlertTitle: 'Email Required',
      emailAlertMessage: 'Please enter a valid email address.',
      zipAlertTitle: 'Zip Code Required',
      zipAlertMessage: 'Please enter a 5-digit Zip Code.',
      zipRestrictionAlertTitle: 'Zip Code Restriction',
      zipRestrictionAlertMessage:
        'You must be a San Francisco resident to participate in iWalk.',
    },
    info: {
      youreSignedUp: 'You’re signed up!',
      fromHereText: 'From here, participation is easy:',
      walk: 'Walk!',
      walkText:
        'This app will count your total steps taken each day, just carry your phone with you when you’re walking.',
      record: 'Record!',
      recordText:
        'Use this feature to track your walks. Challenge yourself to increase distance and time!',
      win: 'Win!',
      winText:
        'At the end of the program, the top 10 walkers will be contacted by email to claim their prize. Prizes include SF Giants merchandise!',
    },
    permissions: {
      thingsToKnow: 'Things to know.',
      takeALookText: 'Take a look at this information before you get started.',
      settingsText: `The iWalk App uses ${Platform.select({
        ios: 'Apple Health',
        android: 'Google Fit',
      })} to keep track of your steps. In the next screens, you will be asked to allow iWalk to use this information.`,
      prizeText: `To win a prize through Intentional Walk, you must allow the iWalk App to use ${Platform.select(
        {ios: 'Apple Health', android: 'Google Fit'},
      )} information. All information will be kept private and used only for the Intentional Walk program.`,
      googleText:
        'Google Fit requires a Google account, if you do not have one, learn how to get one {0}.',
      getOneHere: 'here',
    },
    home: {
      stepsToday: 'steps today',
      milesSuffix: '',
      milesToday: 'miles today',
      overallStepTotal: 'overall step total',
      stepsThisMonth: 'total steps this month',
      topWalkers: 'Top Walkers',
      whereToWalk: 'Where to Walk',
      myRecordedWalks: 'My Recorded Walks Today',
      allRecordedWalks: 'All Recorded Walks',
      noWalksYetText:
        'Start a new walk by pressing the record button at the bottom of the screen.',
      recordAWalk: 'Record a New Walk',
      getReadyAlert1: 'Get ready to start the challenge!',
      getReadyAlert2:
        'On {0}, your step total will reset and your steps will start being counted towards winning prizes.',
      currentAlert: 'Current Walking Challenge: {0} - {1}',
      congratsAlert:
        'Congratulations on all of that great walking! You will receive an email if you are a top walker and have won a prize! The challenge is now over but you can keep using the app to track your steps.',
      noContestAlert: 'No current walking challenge, but keep up the walking!',
      myGoals: 'My Goals',
    },
    whereToWalk: {
      options:
        'The San Francisco Rec & Parks Department has many activity options!',
      parksAndRecCenters: 'Parks & Rec Centers',
      hikingTrailsInSF: 'Hiking Trails in SF',
      guidedWalks: 'Explore Nature',
      exerciseAndFitnessActivities: 'Exercise & Fitness Activities',
    },
    about: {
      what: 'What is Intentional Walk?',
      whatText:
        'Intentional Walk is a FREE community walking program that runs from {0}. The program is open to CalFresh/MediCal-eligible San Francisco residents. Prizes will be awarded to the top walkers at the end of the program.',
      dates: 'What are the key dates?',
      datesText:
        'On {0}, your steps will start at zero and the walking challenge will begin! All of your steps from {1} will count towards winning a prize. After the program is over, you can use the app, but no additional prizes will be awarded.',
      prize: 'How do I win a prize?',
      prizeText:
        'At the end of the program, the top 10 walkers will be contacted by email to claim their prize. Prizes include SF Giants merchandise!',
    },
    latinOrHispanicOrigin: {
      question: 'Are you of Latino or \nHispanic origin?',
      questionSub: '',
      yes: 'Yes',
      no: 'No',
      declineToAnswer: 'Decline to answer',
    },
    whatIsYourRace: {
      question: 'What is your race?',
      questionSub: 'If multiracial, check all that apply',
      americanNative: 'American Indian or\nAlaska Native',
      asian: 'Asian',
      black: 'Black or African American',
      pacificIsl: 'Native Hawaiian or\nOther Pacific Islander',
      white: 'White',
      other: 'Other',
      otherSub: 'Please fill in:',
      cannotBeEmpty: 'This field cannot be empty',
      declineToAnswer: 'Decline to answer',
    },
    whatIsYourGenderIdentity: {
      question: 'What is your gender identity?',
      questionSub: '',
      female: 'Female',
      male: 'Male',
      transFemale: 'Trans Female',
      transMale: 'Trans Male',
      nonBinary: 'Non-Binary',
      other: 'Other',
      otherSub: 'Please fill in:',
      cannotBeEmpty: 'This field cannot be empty',
      declineToAnswer: 'Decline to answer',
    },
    whatIsYourSexualOrientation: {
      question: 'How do you describe your sexual orientation or sexual identy?',
      questionSub: '',
      bisexual: 'Bisexual',
      sameGenderLoving: 'Gay/Lesbian/\nSame-Gender Loving',
      unsure: 'Questioning/Unsure',
      heterosexual: 'Straight/Heterosexual',
      other: 'Other',
      otherSub: 'Please fill in:',
      cannotBeEmpty: 'This field cannot be empty',
      declineToAnswer: 'Decline to answer',
    },
    deleteUser: {
      popupText: 'Are you sure you want to delete ALL of your saved data?',
      yesDelete: 'Yes, delete',
      noGoBack: 'No, go back',
    },
    logout: {
      popupText: 'Are you sure you want to sign out?',
      yesDelete: 'Yes',
      noGoBack: 'No, go back',
    },
    leaderBoard: {
      thisIsYou: 'This is You!',
      walkerGeneral: 'Walker',
    },
    setYourStepGoal: {
      header: 'Set Your Step Goal',
      instructions: 'Tap the buttons to set your step goal',
      stepText: 'I want to walk...',
      daysText: 'How often?',
      decreaseSteps: '-500 steps',
      increaseSteps: '+500 steps',
      decreaseDays: '-1 day',
      increaseDays: '+1 day',
      stepsPerDay: 'steps/day',
      dayPerWeek: 'day/week',
      daysPerWeek: 'days/week',
    },
    stepGoalProgress: {
      thisWeek: 'This Week',
      pastWeek: 'Past Week',
      myGoal: 'My Goal',
      day: 'day',
      days: 'days',
      for: 'for',
      inProgress: 'Goal In Progress',
      goalMet: 'Goal Met',
      goalNotMet: 'Goal Not Met',
      changeMyGoal: 'Change my goal',
      today: 'Today',
      stepsToday: 'steps today',
      avgStepsPerDay: 'average steps/day',
      moreStepsToGo: 'more steps to go',
      totalStepsThisWeek: 'total steps this week',
      mon: 'Mo',
      tue: 'Tu',
      wed: 'We',
      thu: 'Th',
      fri: 'Fr',
      sat: 'Sa',
      sun: 'Su',
    },
  },
  es: {
    common: {
      welcome: 'Bienvenido al Paseo Intencional!!',
      next: 'Siguiente',
      today: 'Hoy',
      yesterday: 'Ayer',
      noWalks: 'No hay caminatas grabadas',
      noWalksYet: 'Todavía no hay caminatas',
      home: 'Inicio',
      back: 'Atrás',
      myRecordedWalks: 'Mis Caminatas Grabadas',
      about: 'Información de iWalk',
      programPartners: 'Socios del Programa',
      topWalkers: 'Mejores caminantes',
      whereToWalk: 'Por Dónde Caminar',
      emailUs: 'Contáctanos',
      contestRules: 'Reglas oficiales del programa',
      privacyPolicy: 'Política de Privacidad',
      signOut: 'Cerrar sesión',
      deleteUser: 'Eliminar cuenta',
      steps: 'pasos',
      miles: 'millas',
      mins: 'minutos',
      morningWalk: 'Caminata Matutina',
      afternoonWalk: 'Caminata por la Tarde',
      eveningWalk: 'Caminata Nocturna',
      okay: 'Está bien',
      pleaseWait: 'Por favor espera...',
      serverErrorTitle: 'Error inesperado',
      serverErrorMessage:
        'No pudimos comunicarnos con el servidor de Caminata Intencional. Por favor verifica tu conexión de internet e intenta nuevamente.',
      date: 'D [de] MMMM',
      range: '{0} al {1}',
      rangeFrom: 'D [de] MMMM',
      rangeTo: 'D [de] MMMM [del] YYYY',
      dateSlash: 'MM/DD/YYYY',
      save: 'Guardar',
    },
    notifications: {
      repeatingRecordingReminder:
        'Has estado caminando por más de una hora. ¡No olvides dejar de grabar tu caminata si ya terminaste!',
    },
    partners: {
      thanks: '¡Un agradecimiento especial a todos los socios de iWalk!',
      text: 'El Paseo Intencional es dirigido por el Departamento de Salud Pública de SF. Está financiado por USDA SNAP, un proveedor y empleador que ofrece igualdad de oportunidades. Los socios comunitarios incluyen el Departamento de Salud Pública de California, Código para San Francisco, los Gigantes de San Francisco y el Departamento de Recreación y Parques de SF.',
    },
    recorder: {
      finish: 'Terminar',
      resume: 'Reiniciar',
      stopAndSave: 'Parar y Guardar',
      stop: 'Parar',
      pause: 'Pausa',
      paused: 'Pausada',
      recording: 'Grabación',
      save: 'Guardando {0}',
    },
    welcome: {
      select: 'Por favor seleccione un idioma.',
      start: 'Iniciar',
    },
    signUp: {
      about:
        'El Paseo Intencional es un programa GRATUITO de caminata comunitaria que se llevará a cabo del {0}. El programa está abierto para residentes de San Francisco elegibles para CalFresh / MediCal. ¡Los mejores caminantes serán elegibles para recibir premios de los Gigantes de San Francisco, incluyendo boletos para el juego, artículos firmados por el equipo y un gran premio especial! ¡Inscríbase para comenzar!',
      name: 'Nombre',
      firstName: 'Primer Nombre',
      lastName: 'Apellido',
      email: 'Correo electrónico',
      zipCode: 'Código postal',
      age: 'Edad',
      required: '*Todos los campos son requeridos',
      agree: 'Al registrarme, acepto la {0} y las {1}.',
      policy: 'Política de Privacidad',
      contestRules: 'Reglas oficiales del programa',
      submit: 'Enviar',
      ageAlertTitle: 'Restricción de Edad',
      ageAlertMessage: 'Debes tener al menos 18 años para participar en iWalk.',
      ageMaxMessage: 'Introduce una edad válida.',
      emailAlertTitle: 'Correo electrónico',
      emailAlertMessage:
        'Por favor, introduce una dirección de correo electrónico válida.',
      zipAlertTitle: 'Código Postal Requerido',
      zipAlertMessage: 'Por favor ingresa un código postal de 5 dígitos.',
      zipRestrictionAlertTitle: 'Restricción de código postal',
      zipRestrictionAlertMessage:
        'Debe ser residente de San Francisco para participar en iWalk.',
    },
    info: {
      youreSignedUp: 'Estas registrado!',
      fromHereText: 'Desde aquí, participar es fácil.',
      walk: '¡Caminar!',
      walkText:
        'Esta aplicación contará los pasos totales que tomas cada día, solo lleva tu teléfono contigo mientras caminas.',
      record: '¡Grabar!',
      recordText:
        'Usa esta función para grabar tus caminatas. ¡Desafíate a ti mismo para aumentar el tiempo y la distancia!',
      win: '¡Ganar!',
      winText:
        'Al final del programa, los 10 mejores caminantes serán contactados por correo electrónico para reclamar su premio. ¡Los premios incluyen mercancía de SF Giants!',
    },
    permissions: {
      thingsToKnow: 'Cosas que debes saber.',
      takeALookText: 'Echa un vistazo a esta información antes de comenzar.',
      settingsText: `La aplicación iWalk utiliza datos recopilados por ${Platform.select(
        {ios: 'Apple Health', android: 'Google Fit'},
      )} para grabar con precisión tus pasos diarios. En las siguientes pantallas, se te pedirá que des permiso para que iWalk acceda a esta información.`,
      prizeText:
        'Todos los participantes que deseen ser elegibles para premios a través del Paseo Intencional deben dar permiso para acceder a esta información. Todos los datos proporcionados se mantendrán privados y se utilizarán estrictamente para el propósito del programa de Paseo Intencional.',
      googleText:
        'Google Fit requiere una cuenta de Google, si no tiene una, aprenda cómo obtenerla {0}.',
      getOneHere: 'aquí',
    },
    home: {
      stepsToday: 'pasos hoy',
      milesSuffix: '',
      milesToday: 'millas hoy',
      overallStepTotal: 'recuento total de pasos',
      stepsThisMonth: 'pasos totales este mes',
      topWalkers: 'Los mejores caminantes',
      whereToWalk: 'Por Dónde Caminar',
      myRecordedWalks: 'Mis Caminatas Grabadas Hoy',
      allRecordedWalks: 'Todas las Caminatas Grabadas',
      noWalksYetText:
        'Comienza una nueva caminata presionando el botón de grabación en la parte inferior de la pantalla.',
      recordAWalk: 'Grabar una Nueva Caminata',
      getReadyAlert1: '¡Prepárate para comenzar el desafío!',
      getReadyAlert2:
        'El {0} tu recuento total de pasos reiniciará y tus pasos comenzarán a ser contados para ganar premios.',
      currentAlert: 'Desafío de caminata actual: {0} - {1}',
      congratsAlert:
        '¡Felicitaciones por esa gran caminata! ¡Recibirás un correo electrónico si eres uno de los mejores caminantes y has ganado un premio! El desafío ya ha terminado, pero puedes seguir usando la aplicación para seguir tus pasos.',
      noContestAlert:
        'Actualmente no hay desafíos para caminar, ¡pero sigue caminando!',
      myGoals: 'Mis metas',
    },
    whereToWalk: {
      options:
        '¡El Departamento de Parques y Recreación de San Francisco tiene muchas opciones de actividades!',
      parksAndRecCenters: 'Parques y Centros de Recreación',
      hikingTrailsInSF: 'Rutas de Senderismo en SF',
      guidedWalks: 'Explorar la Naturaleza',
      exerciseAndFitnessActivities: 'Ejercicio y Actividades Físicas',
    },
    about: {
      what: '¿Qué es el Paseo Intencional?',
      whatText:
        'El Paseo Intencional es un programa GRATUITO de caminata comunitaria que se llevará a cabo del {0}. El programa está abierto para residentes de San Francisco elegibles para CalFresh / MediCal. Se otorgarán premios a los mejores caminantes al final del programa.',
      dates: '¿Cuáles son las fechas importantes?',
      datesText:
        'El {0}, tus pasos comenzarán en cero y el desafío de caminar comenzará! Todos tus pasos del {1} contarán para ganar un premio. Una vez finalizado el programa, puedes utilizar la aplicación, pero no se otorgarán premios adicionales.',
      prize: '¿Cómo gano un premio?',
      prizeText:
        'Al final del programa, los 10 mejores caminantes serán contactados por correo electrónico para reclamar su premio. ¡Los premios incluyen mercancía de SF Giants!',
    },
    latinOrHispanicOrigin: {
      question: '¿Eres de origen latino \no hispano?',
      questionSub: '',
      yes: 'Sí',
      no: 'No',
      declineToAnswer: 'Prefiero no contestar',
    },
    whatIsYourRace: {
      question:
        '¿Cuál es su raza? Si es multirracial, marque todas las que correspondan?',
      questionSub: '',
      americanNative: 'Indio americano o\nnativo de Alaska',
      asian: 'Asiático',
      black: 'Negro o afroamericano',
      pacificIsl: 'Nativo de Hawai u otra\nisla del Pacífico',
      white: 'Blanco',
      other: 'Otro',
      otherSub: 'Por favor complete:',
      cannotBeEmpty: 'Este campo no puede estar vacío',
      declineToAnswer: 'Prefiero no contestar',
    },
    whatIsYourGenderIdentity: {
      question: '¿Cuál es tu identidad de género?',
      questionSub: '',
      female: 'Mujer',
      male: 'Hombre',
      transFemale: 'Mujer trans',
      transMale: 'Hombre trans',
      nonBinary: 'No binario',
      other: 'Otro',
      otherSub: 'Por favor complete:',
      cannotBeEmpty: 'Este campo no puede estar vacío',
      declineToAnswer: 'Prefiero no contestar',
    },
    whatIsYourSexualOrientation: {
      question: '¿Cómo describes tu orientación sexual o identidad sexual?',
      questionSub: '',
      bisexual: 'Bisexual',
      sameGenderLoving: 'Homosexual/Lesbiana/\nAmante del mismo género ',
      unsure: 'Cuestionando/No estoy seguro(a)',
      heterosexual: 'Heterosexual',
      other: 'Otro',
      otherSub: 'Por favor complete:',
      cannotBeEmpty: 'Este campo no puede estar vacío',
      declineToAnswer: 'Prefiero no contestar',
    },
    deleteUser: {
      popupText:
        '¿Está usted seguro de que desea eliminar TODOS sus datos guardados?',
      yesDelete: 'Si, eliminar',
      noGoBack: 'No, regresar',
    },
    logout: {
      popupText: '¿Estás segura de que quieres cerrar sesión?',
      yesDelete: 'Si',
      noGoBack: 'No, regresar',
    },
    leaderBoard: {
      thisIsYou: 'Este es usted!',
      walkerGeneral: 'Caminante',
    },
    setYourStepGoal: {
      header: 'Establece tu meta de pasos',
      instructions: 'Toca los botones para cambiar tu meta de pasos',
      stepText: 'Quiero caminar…',
      daysText: '¿Con qué frecuencia?',
      decreaseSteps: '-500 pasos',
      increaseSteps: '+500 pasos',
      decreaseDays: '-1 día',
      increaseDays: '+1 día',
      stepsPerDay: 'pasos/día',
      dayPerWeek: 'día/semana',
      daysPerWeek: 'días/semana',
    },
    stepGoalProgress: {
      thisWeek: 'Esta Semana',
      pastWeek: 'Semana Pasada',
      myGoal: 'Mi Meta',
      day: 'día',
      days: 'días',
      for: 'durante',
      inProgress: 'META EN CURSO',
      goalMet: 'META CUMPLIDA',
      goalNotMet: 'META NO CUMPLIDA',
      changeMyGoal: 'Cambiar mi meta',
      today: 'HOY',
      stepsToday: 'pasos hoy',
      avgStepsPerDay: 'promedio de pasos/día',
      moreStepsToGo: 'más pasos por recorrer',
      totalStepsThisWeek: 'pasos totales esta semana',
      mon: 'Lu',
      tue: 'Ma',
      wed: 'Mi',
      thu: 'Ju',
      fri: 'Vi',
      sat: 'Sá',
      sun: 'Do',
    },
  },
  zh: {
    common: {
      welcome: '歡迎來到 Intentional Walk!!',
      next: '下一步',
      today: '今天',
      yesterday: '昨天',
      noWalks: '無行走記錄',
      noWalksYet: '還沒有行走',
      home: '家',
      back: '返回',
      myRecordedWalks: '我的步行記錄',
      about: 'iWalk信息',
      programPartners: '計劃合作夥伴',
      topWalkers: '顶级步行者',
      whereToWalk: '去哪裡',
      emailUs: '電郵我們',
      contestRules: '官方程序規則',
      privacyPolicy: '隱私條款',
      signOut: '登出',
      deleteUser: '刪除帳戶',
      steps: '步',
      miles: '英里',
      mins: '分鐘',
      morningWalk: '早上散步',
      afternoonWalk: '下午散步',
      eveningWalk: '傍晚散步',
      okay: '同意',
      pleaseWait: '請稍候...',
      serverErrorTitle: '意外錯誤',
      serverErrorMessage:
        '我們無法與Intentional Walk 服務器通信. 請檢查您的互聯網連接並重試.',
      date: 'M月D日',
      range: '{0}至{1}',
      rangeFrom: 'YYYY[年]M[月]D[日]',
      rangeTo: 'M月D日',
      dateSlash: 'MM/DD/YYYY',
      save: '保存',
    },
    notifications: {
      repeatingRecordingReminder:
        '您已經走了一個多小時. 完成後, 請別忘了停止錄製您的步行記錄!',
    },
    partners: {
      thanks: '特別鳴謝所有iWalk贊助商!',
      text: 'Intentional Walk是由舊金山公共衛生局負責. USDA SNAP資助的一项機會均等提供者和雇主的方案. 社區合作夥伴包括加州公共衛生局, Code of San Franciaco, 舊金山巨人隊和舊金山康樂與公園部.',
    },
    recorder: {
      finish: '完成',
      resume: '重新開始',
      stopAndSave: '停止並保存',
      stop: '停止',
      pause: '暫停',
      paused: '暫停',
      recording: '記錄',
      save: '保存{0}',
    },
    welcome: {
      select: '請選擇一種語言.',
      start: '開始',
    },
    signUp: {
      about:
        'Intentional Walk 是一項於{0}免費運行的社區步行計劃.該計劃向有資格參加CalFresh / Medical的舊金山居民開放. 頂級步行者將有資格獲得舊金山巨人隊的獎品, 其中包括比賽門票, 簽名的裝備和特別獎品! 在下面註冊即可開始!',
      name: '名稱',
      firstName: '名',
      lastName: '姓',
      email: '電子郵件',
      zipCode: '郵政編碼',
      age: '年齡',
      required: '* 需填寫字段',
      agree: '簽署即表示我同意{0}和{1}.',
      policy: '隱私條款',
      contestRules: '官方程序規則',
      submit: '提交',
      ageAlertTitle: '年齡限制',
      ageAlertMessage: '您必須年滿18歲才能參與iWalk。',
      ageMaxMessage: '请输入有效年龄。',
      emailAlertTitle: '需填電子郵件',
      emailAlertMessage: '請輸入有效的電子郵件地址.',
      zipAlertTitle: '需填郵政編碼',
      zipAlertMessage: '請輸入5位數的郵政編碼。',
      zipRestrictionAlertTitle: '郵政編碼限制',
      zipRestrictionAlertMessage: '您必須是舊金山居民才能參加iWalk。',
    },
    info: {
      youreSignedUp: '您已註冊!',
      fromHereText: '從這裡開始，參與很容易.',
      walk: '步行!',
      walkText:
        '這個應用程式會計算您每天要走的總步數，步行時只需隨身攜帶手機即可.',
      record: '記錄!',
      recordText: '使用此功能跟蹤您的行走步數.  增加行走距離和時間來挑戰自我!',
      win: '獲勝!',
      winText:
        '在該計劃結束後會通過電子郵件與前10名步行者聯繫, 以領取獎品. 獎品包括SF Giants商品！',
    },
    permissions: {
      thingsToKnow: '事情需知.',
      takeALookText: '在開始之前請看以下信息.',
      settingsText: `iwalk應用程序使用${Platform.select({
        ios: 'Apple Health',
        android: 'Google Fit',
      })}來跟蹤您的步數. 在下一個屏幕中您將看到允許iWalk使用的信息.`,
      prizeText: `您必須允許iWalk應用程序使用${Platform.select({
        ios: 'Apple Health',
        android: 'Google Fit',
      })}信息才能贏取“Intentional Walk"獎品. 所有信息將保密, 僅用於"Intentional Walk"計劃。`,
      googleText: 'Google Fit需要一個Google帳戶, 如果您沒有Google帳戶, {0}.',
      getOneHere: '請在此處了解如何獲取帳戶',
    },
    home: {
      stepsToday: '今天的步數',
      milesSuffix: '英里',
      milesToday: '今天的路程',
      overallStepTotal: '總步數',
      stepsThisMonth: '今月的總步數',
      topWalkers: '最佳步行者',
      whereToWalk: '去哪裡',
      myRecordedWalks: '我今天的步行記錄',
      allRecordedWalks: '所有的步行記錄',
      noWalksYetText: '按下屏幕底部的“錄製”按鈕來開始新的步行.',
      recordAWalk: '記錄新步數',
      getReadyAlert1: '準備好開始挑戰！',
      getReadyAlert2:
        '從{0}起, 您的步數總數將會重置並且您的步數將開始計入獲獎獎數中.',
      currentAlert: '目前的步行挑戰: {0} - {1}',
      congratsAlert:
        '恭喜您走得這麼好! 如果您是一名頂級步行者, 您將收到一封電子郵件並獲得獎品! 挑戰現已結束, 但您可以繼續使用該應用程序來追踪您的步數.',
      noContestAlert: '目前沒有步行挑戰, 但請繼續行走!',
      myGoals: '我的目標',
    },
    whereToWalk: {
      options: '舊金山娛樂與公園部有很多活動可供選擇!',
      parksAndRecCenters: '公園和娛樂中心',
      hikingTrailsInSF: '舊金山的遠足徑',
      guidedWalks: '探索大自然',
      exerciseAndFitnessActivities: '運動與健身活動',
    },
    about: {
      what: '什麽是Intentional Walk?',
      whatText:
        'Intentional Walk 是一項於{0}免費運行的社區步行計劃.該計劃向有資格參加CalFresh / Medical的舊金山居民開放.',
      dates: '關鍵日期?',
      datesText:
        '挑戰从{0}起, 您的步行數將從零開始! {1}, 您所有的步行數都將計入獎品中. 計劃結束後, 您可以使用該應用程序，但不會獲得其他獎品.',
      prize: '我如何赢取獎品?',
      prizeText:
        '在該計劃結束後會通過電子郵件與前10名步行者聯繫, 以領取獎品. 獎品包括SF Giants商品！',
    },
    latinOrHispanicOrigin: {
      question: '您是拉丁裔還是西班牙裔?',
      questionSub: '',
      yes: '是的',
      no: '不是',
      declineToAnswer: '拒絕回答',
    },
    whatIsYourRace: {
      question: '您的種族是什麽?',
      questionSub: '如果您是多種族, 請勾選所有適用的選項.',
      americanNative: '美洲印第安人或阿拉斯加原住民',
      asian: '亚裔',
      black: '非裔或非裔美國人',
      pacificIsl: '夏威夷原住民或其他太平洋島民',
      white: '白種人',
      other: '其他, 請填寫',
      otherSub: '',
      cannotBeEmpty: '此處不能為空',
      declineToAnswer: '拒絕回答',
    },
    whatIsYourGenderIdentity: {
      question: '您的性别是?',
      questionSub: '',
      female: '女性',
      male: '男性',
      transFemale: '跨性别女性',
      transMale: '跨性别男性',
      nonBinary: '非二元性别',
      other: '其他,',
      otherSub: '請填寫',
      cannotBeEmpty: '此處不能為空',
      declineToAnswer: '拒絕回答',
    },
    whatIsYourSexualOrientation: {
      question: '你如何描述你的性取向或性身份？',
      questionSub: '',
      bisexual: '雙性戀',
      sameGenderLoving: '同性戀(男)/同性戀(女)/同性之戀',
      unsure: '質疑/不確定',
      heterosexual: '異性戀/異性戀者',
      other: '其他,',
      otherSub: '請填寫',
      cannotBeEmpty: '此處不能為空',
      declineToAnswer: '拒絕回答',
    },
    deleteUser: {
      popupText: '您確定要刪除您所有儲存下來的資料嗎？',
      yesDelete: '是，刪除',
      noGoBack: '否，返回',
    },
    logout: {
      popupText: '您确定要退出吗？',
      yesDelete: '是',
      noGoBack: '否，返回',
    },
    leaderBoard: {
      thisIsYou: '您在這裡',
      walkerGeneral: '沃克',
    },
    setYourStepGoal: {
      header: '設定您的步數目標',
      instructions: '點擊按鈕來更改您的步數目標',
      stepText: '我想步行...',
      daysText: '多久一次？',
      decreaseSteps: '-500 步',
      increaseSteps: '+500 步',
      decreaseDays: '-1 天',
      increaseDays: '+1 天',
      stepsPerDayBefore: '每天',
      stepsPerDay: '步',
      daysPerWeekBefore: '每週',
      dayPerWeek: '天',
      daysPerWeek: '天',
    },
    stepGoalProgress: {
      thisWeek: '本周',
      pastWeek: '上週',
      myGoal: '我的目標',
      day: '天',
      days: '天',
      for: '每週',
      inProgress: '目標進展',
      goalMet: '達到目標',
      goalNotMet: '未達到目標',
      changeMyGoal: '改變我的目標',
      today: '今天',
      stepsToday: '今天的步數',
      avgStepsPerDay: '平均步數/天',
      moreStepsToGo: '還需增加更多步數',
      totalStepsThisWeek: '本週總步數',
      mon: '一',
      tue: '二',
      wed: '三',
      thu: '四',
      fri: '五',
      sat: '六',
      sun: '日',
    },
  },
});

export default Strings;
